schema_version: 1

context:
  org: openforcefield
  name: openff-units
  version: "0.4.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/${{ org }}/${{ name }}/archive/refs/tags/${{ version }}.tar.gz
  sha256: 8df8ec4307769bc6473b87c0641a8eafb56eef4ff87cc10ba05eb6de362c26a6

build:
  number: 1
  noarch: python
  script: SETUPTOOLS_SCM_PRETEND_VERSION=${{ version }} ${{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - setuptools_scm
    - pip
  run:
    - python >=${{ python_min }},<3.15.0a0
    - numpy
    - pint >=0.24.0,<0.26
    - openff-utilities
  run_constraints:
    - openmm >7.6
    - pydantic >=2.13  # 2.12 might work (untested), older might also work (less likely)

tests:
  - python:
      imports:
        - openff.units
        - openff.units.openmm
        - openff.units.elements
      pip_check: false
      python_version: ${{ python_min }}.*
  - files:
      recipe:
        - test_units.py
    requirements:
      run:
        - python ${{ python_min }}.*
        - setuptools
        - openmm
        - pydantic
    script:
      - python test_units.py

about:
  license: MIT
  license_file: LICENSE
  summary: A common units module for the OpenFF software stack
  homepage: https://openforcefield.org/
  repository: https://github.com/openforcefield/openff-units

extra:
  recipe-maintainers:
    - mattwthompson
    - j-wags

